export {
  ZettaPayClient,
  X402_HEADER,
  type ZettaPayClientOptions,
  type PayInput,
} from './client.js';
export { ZettaPayError, fromAxiosError } from './errors.js';
export type {
  ApiErrorBody,
  HealthStatus,
  ListMerchantsOptions,
  ListMerchantsResponse,
  ListPaymentsOptions,
  ListPaymentsResponse,
  Merchant,
  PayResponse,
  PaymentRecord,
  RegisterMerchantInput,
  UpdateMerchantInput,
} from './types.js';
export {
  ZETTAPAY_PROGRAM_ID,
  MERCHANT_HANDLE_MIN_LEN,
  MERCHANT_HANDLE_MAX_LEN,
  PAYMENT_ID_LEN,
  TX_SIGNATURE_LEN,
  INVOICE_INDEX_SEED_LEN,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  USDC_MINT,
  isValidMerchantHandle,
  deriveMerchantBindingPda,
  derivePaymentPda,
  deriveInvoicePda,
  deriveAssociatedTokenAddress,
  deriveInvoiceUsdcAddress,
  buildRegisterMerchantInstruction,
  buildRecordPaymentInstruction,
  registerMerchantOnChain,
  recordPayment,
  type PdaAddress,
  type UsdcCluster,
  type DeriveInvoiceUsdcAddressParams,
  type InvoiceUsdcAddress,
  type BuildRegisterMerchantParams,
  type BuildRecordPaymentParams,
  type RegisterMerchantOnChainParams,
  type RecordPaymentOnChainParams,
  type SendOnChainResult,
} from './onchain.js';
export { ZETTAPAY_IDL, type ZettaPayErrorCode } from './idl/zettapay.js';
export {
  HARDENED_OFFSET,
  XPUB_VERSIONS,
  parseXpub,
  serializeXpub,
  deriveChildPub,
  derivePath,
  parsePath,
  fingerprintOf,
  uncompressedPubKey,
  base58Encode,
  base58Decode,
  base58CheckEncode,
  base58CheckDecode,
  sha256d,
  hash160,
  type ExtendedPublicKey,
  type Bip32Network,
} from './bip32.js';
export {
  USDC_EVM_CONTRACTS,
  BIP44_COIN,
  BTC_P2PKH_VERSION,
  toEip55,
  compressedPubKeyToBtcAddress,
  compressedPubKeyToEthAddress,
  deriveBitcoinAddress,
  deriveEthereumAddress,
  deriveUsdcEvmAddress,
  type EvmChain,
  type BtcNetwork,
  type DeriveOptions,
  type UsdcDeriveOptions,
  type BitcoinDerivation,
  type EthereumDerivation,
  type UsdcEvmDerivation,
} from './crosschain.js';
export {
  parseWebhook,
  dedupe,
  MemoryEventStore,
  SIGNATURE_HEADER,
  TIMESTAMP_HEADER,
  EVENT_ID_HEADER,
  ATTEMPT_HEADER,
  type ParseWebhookOptions,
  type ParseWebhookResult,
  type ParsedWebhook,
  type WebhookFailureReason,
  type EventStore,
  type DedupeResult,
  type HeaderBag,
} from './webhook.js';
